name: Deploy to EC2

on:
  pull_request_review:
    types:
      - submitted

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: action
        uses: actions/checkout@v3

      - name: SSH Key
        run: |
          echo "${{ secrets.SSHKEY }}" | base64 --decode > ec2-key.pem
          chmod 400 ec2-key.pem

      - name: Install Apache on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ec2-key.pem ubuntu@3.84.202.139
          sudo apt update -y
          sudo apt install apache2 -y
          sudo systemctl start apache2
          sudo systemctl enable apache2

          echo "<h1>Hello, apache is running(pull request)</h1>" | sudo tee /var/www/html/index.html
